[build]
  publish = "frontend/dist"
  command = "cd frontend && npm install && npm run build"

[dev]
  command = "npm run dev --prefix frontend"
  port = 5173

[[redirects]]
  from = "/api/*"
  to = "http://localhost:4000/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
